version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /security-console
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /legacy-static
    schedule:
      interval: weekly