/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Vehicle = {
  _id: string;
  _type: "vehicle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  stockNumber: string;
  vin: string;
  slug: string;
  year: number;
  make: string;
  model: string;
  trim?: string;
  price: number;
  mileage: number;
  exteriorColor?: string;
  interiorColor?: string;
  bodyStyle?: string;
  transmission?: string;
  drivetrain?: string;
  fuelType?: string;
  engine?: string;
  description?: string;
  features?: Array<string>;
  photographs?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  }>;
  status: "draft" | "published" | "pending" | "sold" | "archived";
  version?: number;
  createdAt?: string;
  updatedAt?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Vehicle
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../Speedzone/src/lib/server/inventory.ts
// Variable: ALL_VEHICLES_QUERY
// Query: *[_type == "vehicle" && !(_id in path("drafts.**"))]  | order(coalesce(updatedAt, _updatedAt) desc) {    _id, _rev, _createdAt, _updatedAt,    version, createdAt, updatedAt,    stockNumber, vin, year, make, model, trim, price, mileage,    exteriorColor, interiorColor, bodyStyle, transmission, drivetrain,    fuelType, engine, description, features, status, slug,    photographs[]{      _key, _type, alt, url, pathname, width, height, bytes, createdAt,      asset->{_id, _createdAt, url, size, metadata{dimensions{width, height}}}    }  }
export type ALL_VEHICLES_QUERY_RESULT = Array<{
  _id: string;
  _rev: string;
  _createdAt: string;
  _updatedAt: string;
  version: number | null;
  createdAt: string | null;
  updatedAt: string | null;
  stockNumber: string;
  vin: string;
  year: number;
  make: string;
  model: string;
  trim: string | null;
  price: number;
  mileage: number;
  exteriorColor: string | null;
  interiorColor: string | null;
  bodyStyle: string | null;
  transmission: string | null;
  drivetrain: string | null;
  fuelType: string | null;
  engine: string | null;
  description: string | null;
  features: Array<string> | null;
  status: "archived" | "draft" | "pending" | "published" | "sold";
  slug: string;
  photographs: Array<{
    _key: string;
    _type: "image";
    alt: string;
    url: null;
    pathname: null;
    width: null;
    height: null;
    bytes: null;
    createdAt: null;
    asset: {
      _id: string;
      _createdAt: string;
      url: string;
      size: number;
      metadata: {
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
  }> | null;
}>;

// Source: ../Speedzone/src/lib/server/inventory.ts
// Variable: PUBLISHED_VEHICLES_QUERY
// Query: *[_type == "vehicle" && !(_id in path("drafts.**")) && status == "published"]  | order(coalesce(updatedAt, _updatedAt) desc) {    _id, _rev, _createdAt, _updatedAt,    version, createdAt, updatedAt,    stockNumber, vin, year, make, model, trim, price, mileage,    exteriorColor, interiorColor, bodyStyle, transmission, drivetrain,    fuelType, engine, description, features, status, slug,    photographs[]{      _key, _type, alt, url, pathname, width, height, bytes, createdAt,      asset->{_id, _createdAt, url, size, metadata{dimensions{width, height}}}    }  }
export type PUBLISHED_VEHICLES_QUERY_RESULT = Array<{
  _id: string;
  _rev: string;
  _createdAt: string;
  _updatedAt: string;
  version: number | null;
  createdAt: string | null;
  updatedAt: string | null;
  stockNumber: string;
  vin: string;
  year: number;
  make: string;
  model: string;
  trim: string | null;
  price: number;
  mileage: number;
  exteriorColor: string | null;
  interiorColor: string | null;
  bodyStyle: string | null;
  transmission: string | null;
  drivetrain: string | null;
  fuelType: string | null;
  engine: string | null;
  description: string | null;
  features: Array<string> | null;
  status: "archived" | "draft" | "pending" | "published" | "sold";
  slug: string;
  photographs: Array<{
    _key: string;
    _type: "image";
    alt: string;
    url: null;
    pathname: null;
    width: null;
    height: null;
    bytes: null;
    createdAt: null;
    asset: {
      _id: string;
      _createdAt: string;
      url: string;
      size: number;
      metadata: {
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
  }> | null;
}>;

// Source: ../Speedzone/src/lib/server/inventory.ts
// Variable: PUBLISHED_VEHICLE_BY_SLUG_QUERY
// Query: *[_type == "vehicle" && !(_id in path("drafts.**")) && status == "published" && slug == $slug][0] {    _id, _rev, _createdAt, _updatedAt,    version, createdAt, updatedAt,    stockNumber, vin, year, make, model, trim, price, mileage,    exteriorColor, interiorColor, bodyStyle, transmission, drivetrain,    fuelType, engine, description, features, status, slug,    photographs[]{      _key, _type, alt, url, pathname, width, height, bytes, createdAt,      asset->{_id, _createdAt, url, size, metadata{dimensions{width, height}}}    }  }
export type PUBLISHED_VEHICLE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _rev: string;
  _createdAt: string;
  _updatedAt: string;
  version: number | null;
  createdAt: string | null;
  updatedAt: string | null;
  stockNumber: string;
  vin: string;
  year: number;
  make: string;
  model: string;
  trim: string | null;
  price: number;
  mileage: number;
  exteriorColor: string | null;
  interiorColor: string | null;
  bodyStyle: string | null;
  transmission: string | null;
  drivetrain: string | null;
  fuelType: string | null;
  engine: string | null;
  description: string | null;
  features: Array<string> | null;
  status: "archived" | "draft" | "pending" | "published" | "sold";
  slug: string;
  photographs: Array<{
    _key: string;
    _type: "image";
    alt: string;
    url: null;
    pathname: null;
    width: null;
    height: null;
    bytes: null;
    createdAt: null;
    asset: {
      _id: string;
      _createdAt: string;
      url: string;
      size: number;
      metadata: {
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
  }> | null;
} | null;

// Source: ../Speedzone/src/lib/server/inventory.ts
// Variable: VEHICLE_BY_ID_QUERY
// Query: *[_type == "vehicle" && !(_id in path("drafts.**")) && _id == $id][0] {    _id, _rev, _createdAt, _updatedAt,    version, createdAt, updatedAt,    stockNumber, vin, year, make, model, trim, price, mileage,    exteriorColor, interiorColor, bodyStyle, transmission, drivetrain,    fuelType, engine, description, features, status, slug,    photographs[]{      _key, _type, alt, url, pathname, width, height, bytes, createdAt,      asset->{_id, _createdAt, url, size, metadata{dimensions{width, height}}}    }  }
export type VEHICLE_BY_ID_QUERY_RESULT = {
  _id: string;
  _rev: string;
  _createdAt: string;
  _updatedAt: string;
  version: number | null;
  createdAt: string | null;
  updatedAt: string | null;
  stockNumber: string;
  vin: string;
  year: number;
  make: string;
  model: string;
  trim: string | null;
  price: number;
  mileage: number;
  exteriorColor: string | null;
  interiorColor: string | null;
  bodyStyle: string | null;
  transmission: string | null;
  drivetrain: string | null;
  fuelType: string | null;
  engine: string | null;
  description: string | null;
  features: Array<string> | null;
  status: "archived" | "draft" | "pending" | "published" | "sold";
  slug: string;
  photographs: Array<{
    _key: string;
    _type: "image";
    alt: string;
    url: null;
    pathname: null;
    width: null;
    height: null;
    bytes: null;
    createdAt: null;
    asset: {
      _id: string;
      _createdAt: string;
      url: string;
      size: number;
      metadata: {
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
  }> | null;
} | null;

// Source: ../Speedzone/src/lib/server/inventory.ts
// Variable: VEHICLE_UNIQUENESS_QUERY
// Query: *[    _type == "vehicle" &&    !(_id in path("drafts.**")) &&    _id != $excludeVehicleId &&    (lower(stockNumber) == lower($stockNumber) || lower(vin) == lower($vin) || lower(slug) == lower($slug))  ]{_id, stockNumber, vin, slug}
export type VEHICLE_UNIQUENESS_QUERY_RESULT = Array<{
  _id: string;
  stockNumber: string;
  vin: string;
  slug: string;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "vehicle" && !(_id in path("drafts.**"))]\n  | order(coalesce(updatedAt, _updatedAt) desc) {\n    _id, _rev, _createdAt, _updatedAt,\n    version, createdAt, updatedAt,\n    stockNumber, vin, year, make, model, trim, price, mileage,\n    exteriorColor, interiorColor, bodyStyle, transmission, drivetrain,\n    fuelType, engine, description, features, status, slug,\n    photographs[]{\n      _key, _type, alt, url, pathname, width, height, bytes, createdAt,\n      asset->{_id, _createdAt, url, size, metadata{dimensions{width, height}}}\n    }\n  }\n': ALL_VEHICLES_QUERY_RESULT;
    '\n  *[_type == "vehicle" && !(_id in path("drafts.**")) && status == "published"]\n  | order(coalesce(updatedAt, _updatedAt) desc) {\n    _id, _rev, _createdAt, _updatedAt,\n    version, createdAt, updatedAt,\n    stockNumber, vin, year, make, model, trim, price, mileage,\n    exteriorColor, interiorColor, bodyStyle, transmission, drivetrain,\n    fuelType, engine, description, features, status, slug,\n    photographs[]{\n      _key, _type, alt, url, pathname, width, height, bytes, createdAt,\n      asset->{_id, _createdAt, url, size, metadata{dimensions{width, height}}}\n    }\n  }\n': PUBLISHED_VEHICLES_QUERY_RESULT;
    '\n  *[_type == "vehicle" && !(_id in path("drafts.**")) && status == "published" && slug == $slug][0] {\n    _id, _rev, _createdAt, _updatedAt,\n    version, createdAt, updatedAt,\n    stockNumber, vin, year, make, model, trim, price, mileage,\n    exteriorColor, interiorColor, bodyStyle, transmission, drivetrain,\n    fuelType, engine, description, features, status, slug,\n    photographs[]{\n      _key, _type, alt, url, pathname, width, height, bytes, createdAt,\n      asset->{_id, _createdAt, url, size, metadata{dimensions{width, height}}}\n    }\n  }\n': PUBLISHED_VEHICLE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "vehicle" && !(_id in path("drafts.**")) && _id == $id][0] {\n    _id, _rev, _createdAt, _updatedAt,\n    version, createdAt, updatedAt,\n    stockNumber, vin, year, make, model, trim, price, mileage,\n    exteriorColor, interiorColor, bodyStyle, transmission, drivetrain,\n    fuelType, engine, description, features, status, slug,\n    photographs[]{\n      _key, _type, alt, url, pathname, width, height, bytes, createdAt,\n      asset->{_id, _createdAt, url, size, metadata{dimensions{width, height}}}\n    }\n  }\n': VEHICLE_BY_ID_QUERY_RESULT;
    '\n  *[\n    _type == "vehicle" &&\n    !(_id in path("drafts.**")) &&\n    _id != $excludeVehicleId &&\n    (lower(stockNumber) == lower($stockNumber) || lower(vin) == lower($vin) || lower(slug) == lower($slug))\n  ]{_id, stockNumber, vin, slug}\n': VEHICLE_UNIQUENESS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
