import Link from "next/link";
import { LogoutButton } from "@/app/Security_Console/auth-client";
import { requireMfa } from "@/lib/security-console/guards";
import { configurationHealth, dashboardSummary, eventGroups } from "@/lib/security-console/dashboard";
import { readEvents, type SecurityEvent } from "@/lib/security-console/security-store";
import { readConsoleAudit, type ConsoleAuditEvent } from "@/lib/security-console/console-audit";
import { listSecuritySessions, type VisibleSecuritySession } from "@/lib/security-console/auth";

export const dynamic = "force-dynamic";

function date(value?: string) { return value ? new Date(value).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }) + " UTC" : "No events received"; }
function location(event: SecurityEvent) { return [event.client?.region, event.client?.country].filter(Boolean).join(", ") || "Unavailable"; }

function EventTable({ events, empty }: { events: SecurityEvent[]; empty: string }) {
  if (!events.length) return <p className="muted">{empty}</p>;
  return <div className="table-wrap"><table><thead><tr><th>Time</th><th>Event</th><th>Outcome</th><th>Network</th><th>Location / client</th><th>Request</th></tr></thead><tbody>{events.slice(0,100).map(event => <tr key={event.id}><td>{date(event.occurredAt)}</td><td><Link href={`/Security_Console/events/${event.id}`}><strong>{event.event}</strong></Link><br/><span className="muted">{event.reason || "No reason recorded"}</span></td><td><span className={`badge ${event.outcome === "allowed" ? "" : "danger"}`}>{event.outcome}</span></td><td className="mono">{event.client?.networkFingerprint || "Unavailable"}</td><td>{location(event)}<br/><span className="muted">{event.client?.userAgentFamily || "Unavailable"}</span></td><td className="mono">{event.requestId}</td></tr>)}</tbody></table></div>;
}

function ConsoleAuditTable({events}:{events:ConsoleAuditEvent[]}){
  if(!events.length)return <p className="muted">No console access events are available.</p>;
  return <div className="table-wrap"><table><thead><tr><th>Time</th><th>Operation</th><th>Outcome</th><th>Network</th><th>Country / client</th></tr></thead><tbody>{events.map(event=><tr key={event.id}><td>{date(event.occurredAt)}</td><td><strong>{event.event}</strong><br/><span className="muted">{event.reason}</span></td><td><span className={`badge ${event.outcome==="allowed"?"":"danger"}`}>{event.outcome}</span></td><td className="mono">{event.networkFingerprint||"Unavailable"}</td><td>{event.country||"Unavailable"}<br/><span className="muted">{event.userAgentFamily||"Unavailable"}</span></td></tr>)}</tbody></table></div>;
}

function SessionTable({sessions}:{sessions:VisibleSecuritySession[]}){if(!sessions.length)return <p className="muted">No indexed active sessions.</p>;return <div className="table-wrap"><table><thead><tr><th>Session</th><th>Created</th><th>Last activity</th><th>Level</th></tr></thead><tbody>{sessions.map(session=><tr key={session.id}><td className="mono">{session.id}{session.current?" (current)":""}</td><td>{date(new Date(session.createdAt).toISOString())}</td><td>{date(new Date(session.lastSeenAt).toISOString())}</td><td>{session.level}</td></tr>)}</tbody></table></div>}

export default async function Page() {
  await requireMfa();
  let events: SecurityEvent[]=[]; let consoleEvents:ConsoleAuditEvent[]=[];let sessions:VisibleSecuritySession[]=[]; let unavailable=false; let consoleAuditUnavailable=false;
  try { events=await readEvents(500); } catch { unavailable=true; }
  try { [consoleEvents,sessions]=await Promise.all([readConsoleAudit(100),listSecuritySessions()]); } catch { consoleAuditUnavailable=true; }
  const groups=eventGroups(events); const summary=dashboardSummary(events); const configuration=configurationHealth();
  return <main><header><div><p className="eyebrow">SpeedZone / security operations</p><h1>Security headquarters</h1><p className="muted">Read-only visibility across website access, inventory operations, reports, and delivery health.</p></div><nav><a href="#admin-access">Admin access</a><a href="#inventory">Inventory</a><Link href="/Security_Console/integrity">Integrity</Link><Link href="/Security_Console/passkeys">Passkeys</Link><LogoutButton/></nav></header>
    {unavailable && <section className="notice danger">The security-event provider is unavailable. Configuration status remains visible below.</section>}
    <section aria-labelledby="overview"><h2 id="overview">Overview</h2><div className="metric-grid"><div className="panel"><span className="muted">Successful admin logins / 24h</span><div className="value">{summary.successfulLogins}</div></div><div className="panel"><span className="muted">Failed admin logins / 24h</span><div className="value">{summary.failedLogins}</div></div><div className="panel"><span className="muted">Operational failures / 24h</span><div className="value">{summary.operationalFailures}</div></div><div className="panel"><span className="muted">Bug reports / 24h</span><div className="value">{summary.reports}</div></div><div className="panel"><span className="muted">Inventory mutations / 24h</span><div className="value">{summary.inventoryMutations}</div></div><div className="panel"><span className="muted">Single-seen networks</span><div className="value">{summary.newNetworks}</div></div></div></section>
    <section className="panel section" id="admin-access"><h2>Admin access</h2><p className="muted">Password and passkey outcomes, rate limits, session lifecycle, and privacy-safe network context.</p><EventTable events={groups.adminAccess} empty="No administrator access events are available."/></section>
    <section className="panel section" id="credentials"><h2>Credential history</h2><p className="muted">Password recovery, password changes, passkey operations, and credential epochs. Secret material is excluded at event creation.</p><EventTable events={groups.credentials} empty="No credential-history events are available."/></section>
    <section className="panel section" id="inventory"><h2>Inventory activity</h2><p className="muted">Catalog mutations, uploads, conflicts, and storage outcomes. This console cannot modify inventory.</p><EventTable events={groups.inventory} empty="No inventory events are available."/></section>
    <section className="panel section" id="reports"><h2>Bug and security reports</h2><p className="muted">Encrypted report receipt is visible without exposing report contents in the event provider. Decrypted details use a signed, read-only server path.</p><p><Link className="text-link" href="/Security_Console/reports">Open encrypted report inbox</Link></p><EventTable events={groups.reports} empty="No bug or security report events are available."/></section>
    <section className="panel section" id="customers"><h2>Customer-request health</h2><div className="split"><div><strong>Accepted requests</strong><div className="value">{groups.customers.filter(event=>event.event==="test-drive.submission"&&event.outcome==="allowed").length}</div></div><div><strong>Delivered notifications</strong><div className="value">{groups.customers.filter(event=>event.event==="test-drive.notification"&&event.outcome==="allowed").length}</div></div><div><strong>Notification failures</strong><div className="value">{groups.customers.filter(event=>event.event==="test-drive.notification"&&event.outcome!=="allowed").length}</div></div></div><EventTable events={groups.customers} empty="No customer-request events are available."/></section>
    <section className="panel section" id="integrity"><h2>Audit integrity</h2><div className="split"><div><strong>Last received</strong><p>{date(summary.lastReceivedAt)}</p></div><div><strong>Invalid hashes</strong><p>{summary.invalidHashes}</p></div><div><strong>Unsupported schemas</strong><p>{summary.unsupportedVersions}</p></div><div><strong>Largest observed interval</strong><p>{summary.largestGapMs ? `${Math.round(summary.largestGapMs/60000)} minutes` : "Insufficient data"}</p></div></div><h3>Configuration health</h3><div className="config-list">{configuration.map(item=><div key={item.key}><code>{item.key}</code><span className={`badge ${item.status === "SET" ? "" : "danger"}`}>{item.status}</span></div>)}</div><p><Link className="text-link" href="/Security_Console/integrity">Run the controlled delivery test</Link></p></section>
    <section className="panel section" id="console-access"><h2>Security Console access</h2><p>Console authentication uses an independent password, passkeys, cookie, credential epoch, and session generation.</p><p><Link className="text-link" href="/Security_Console/passkeys">Manage enrolled console passkeys</Link></p>{consoleAuditUnavailable?<p className="danger">The independent console audit index is unavailable.</p>:<><h3>Active sessions</h3><SessionTable sessions={sessions}/><h3>Console authentication history</h3><ConsoleAuditTable events={consoleEvents}/></>}<p className="muted">This access history and session index are stored only in the console’s independent Redis database.</p></section>
  </main>;
}
