import type { Metadata, Viewport } from "next";
import { connection } from "next/server";
import type { ReactNode } from "react";

import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://www.speedzonems.com"),
  title: {
    default: "SpeedZone Motorsports | Affordable Used Cars in Worcester, MA",
    template: "%s | SpeedZone Motorsports",
  },
  description:
    "Find quality, affordable used cars at SpeedZone Motorsports in Worcester, Massachusetts.",
  icons: {
    icon: "/assets/speedzone-logo-v1.png",
    apple: "/assets/speedzone-logo-v1.png",
  },
  manifest: "/manifest.webmanifest",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#020202",
  colorScheme: "dark",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  // A per-request render lets Next attach the strict CSP nonce generated by
  // proxy.ts to framework and application scripts.
  await connection();
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body>{children}</body>
    </html>
  );
}
